# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 363563b5303163fe2401f99752ea17791db24963d6d209007bb346eb5ae2d2590b5884ed52258af7d27c56167c7fc437966bc3229795ac13cd8603cbf6011aa1

test:
  secret_key_base: 79c8b416efba729d712fd859b1977b09c666fb90ac802d2ef2e383fe307d095cf3eea6548660fc8e4755afd665646a5f76bc166ce379775fa4aa4b0c8119ba1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
